Updated GitHub Actions CI config.
Added new gcc and clang versions, added MSYS/MinGW and Cygwin jobs.
Also increased job timeouts to allow for some slack due to networking
slowdowns and delays in CI.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-# Copyright 2021-2025 Andrey Semashev
+# Copyright 2021-2026 Andrey Semashev
 #
 # Distributed under the Boost Software License, Version 1.0.
 # (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)
@@ -149,33 +149,42 @@ jobs:
             cxxstd64: "11,14,17,20,23,26,11-gnu,14-gnu,17-gnu,20-gnu,23-gnu,26-gnu"
             cxxstd32: "11,11-gnu"
             os: ubuntu-latest
-            container: ubuntu:25.04
+            container: ubuntu:26.04
             install:
               - g++-15
               - g++-15-multilib
               - linux-libc-dev:i386
+          - toolset: gcc-16
+            cxxstd64: "11,14,17,20,23,26,11-gnu,14-gnu,17-gnu,20-gnu,23-gnu,26-gnu"
+            cxxstd32: "11,11-gnu"
+            os: ubuntu-latest
+            container: ubuntu:26.04
+            install:
+              - g++-16
+              - g++-16-multilib
+              - linux-libc-dev:i386
           - name: UBSAN
-            toolset: gcc-13
-            cxxstd64: "11,14,17,20,23,11-gnu,14-gnu,17-gnu,20-gnu,23-gnu"
+            toolset: gcc-15
+            cxxstd64: "11,14,17,20,23,11-gnu,14-gnu,17-gnu,20-gnu,23-gnu,26-gnu"
             cxxstd32: "11,11-gnu"
             ubsan: 1
             build_variant: debug
             os: ubuntu-latest
-            container: ubuntu:24.04
+            container: ubuntu:26.04
             install:
-              - g++-13
-              - g++-13-multilib
+              - g++-15
+              - g++-15-multilib
               - linux-libc-dev:i386
           - name: TSAN
-            toolset: gcc-13
-            cxxstd64: "11,14,17,20,23,11-gnu,14-gnu,17-gnu,20-gnu,23-gnu"
+            toolset: gcc-15
+            cxxstd64: "11,14,17,20,23,11-gnu,14-gnu,17-gnu,20-gnu,23-gnu,26-gnu"
             tsan: 1
             build_variant: debug
             os: ubuntu-latest
-            container: ubuntu:24.04
+            container: ubuntu:26.04
             install:
-              - g++-13
-              - g++-13-multilib
+              - g++-15
+              - g++-15-multilib
 
           # Linux, clang
           - toolset: clang
@@ -388,59 +397,81 @@ jobs:
             cxxstd64: "11,14,17,20,23,26,11-gnu,14-gnu,17-gnu,20-gnu,23-gnu,26-gnu"
             cxxstd32: "11,11-gnu"
             os: ubuntu-latest
-            container: ubuntu:25.04
+            container: ubuntu:26.04
             install:
               - clang-20
-              - g++-13
-              - g++-13-multilib
+              - g++-15
+              - g++-15-multilib
               - linux-libc-dev:i386
           - toolset: clang
-            compiler: clang++-20
+            compiler: clang++-21
+            cxxstd64: "11,14,17,20,23,26,11-gnu,14-gnu,17-gnu,20-gnu,23-gnu,26-gnu"
+            cxxstd32: "11,11-gnu"
+            os: ubuntu-latest
+            container: ubuntu:26.04
+            install:
+              - clang-21
+              - g++-15
+              - g++-15-multilib
+              - linux-libc-dev:i386
+          - toolset: clang
+            compiler: clang++-22
+            cxxstd64: "11,14,17,20,23,26,11-gnu,14-gnu,17-gnu,20-gnu,23-gnu,26-gnu"
+            cxxstd32: "11,11-gnu"
+            os: ubuntu-latest
+            container: ubuntu:26.04
+            install:
+              - clang-22
+              - g++-15
+              - g++-15-multilib
+              - linux-libc-dev:i386
+          - toolset: clang
+            compiler: clang++-22
             cxxstd64: "11,14,17,20,23,26"
             cxxflags: -stdlib=libc++
             linkflags: -stdlib=libc++
             os: ubuntu-latest
-            container: ubuntu:25.04
+            container: ubuntu:26.04
             install:
-              - clang-20
-              - libc++-20-dev
-              - libc++abi-20-dev
+              - clang-22
+              - libc++-22-dev
+              - libc++abi-22-dev
           - name: UBSAN
             toolset: clang
-            compiler: clang++-18
+            compiler: clang++-22
             cxxstd64: "11,14,17,20,23,26,11-gnu,14-gnu,17-gnu,20-gnu,23-gnu,26-gnu"
             cxxflags: -stdlib=libc++
             linkflags: -stdlib=libc++
             ubsan: 1
             build_variant: debug
-            os: ubuntu-24.04
+            os: ubuntu-26.04
             install:
-              - clang-18
-              - libc++-18-dev
-              - libc++abi-18-dev
+              - clang-22
+              - libc++-22-dev
+              - libc++abi-22-dev
           - name: TSAN
             toolset: clang
-            compiler: clang++-18
+            compiler: clang++-22
             cxxstd64: "11,14,17,20,23,26,11-gnu,14-gnu,17-gnu,20-gnu,23-gnu,26-gnu"
             cxxflags: -stdlib=libc++
             linkflags: -stdlib=libc++
             tsan: 1
             build_variant: debug
-            os: ubuntu-24.04
+            os: ubuntu-26.04
             install:
-              - clang-18
-              - libc++-18-dev
-              - libc++abi-18-dev
+              - clang-22
+              - libc++-22-dev
+              - libc++abi-22-dev
 
           - name: ARM
-            toolset: gcc-13
-            cxxstd64: "11,14,17,20,23,11-gnu,14-gnu,17-gnu,20-gnu,23-gnu"
+            toolset: gcc-15
+            cxxstd64: "11,14,17,20,23,11-gnu,14-gnu,17-gnu,20-gnu,23-gnu,26-gnu"
             cxxstd32: "11,11-gnu"
             instruction_set: "-"
-            os: ubuntu-24.04-arm
-            container: ubuntu:24.04
+            os: ubuntu-26.04-arm
+            container: ubuntu:26.04
             install:
-              - g++-13
+              - g++-15
 
           - toolset: clang
             vm: freebsd
@@ -489,9 +520,9 @@ jobs:
 
           - name: CMake tests
             cmake_tests: 1
-            os: ubuntu-22.04
+            os: ubuntu-24.04
 
-    timeout-minutes: 30
+    timeout-minutes: 60
     runs-on: ${{matrix.os}}
     container: ${{matrix.container}}
 
@@ -708,11 +739,11 @@ jobs:
             if [ -n "${{matrix.ubsan}}" ]
             then
                 export UBSAN_OPTIONS="print_stacktrace=1"
-                B2_ARGS+=("cxxflags=-fsanitize=undefined -fno-sanitize-recover=undefined" "linkflags=-fsanitize=undefined -fuse-ld=gold" "define=UBSAN=1" "debug-symbols=on" "visibility=global")
+                B2_ARGS+=("cxxflags=-fsanitize=undefined -fno-sanitize-recover=undefined" "linkflags=-fsanitize=undefined" "define=UBSAN=1" "debug-symbols=on" "visibility=global")
             fi
             if [ -n "${{matrix.tsan}}" ]
             then
-                B2_ARGS+=("cxxflags=-fsanitize=thread" "linkflags=-fsanitize=thread -fuse-ld=gold" "define=TSAN=1" "debug-symbols=on" "visibility=global")
+                B2_ARGS+=("cxxflags=-fsanitize=thread" "linkflags=-fsanitize=thread" "define=TSAN=1" "debug-symbols=on" "visibility=global")
             fi
             if [ -n "${{matrix.cxxflags}}" ]
             then
@@ -951,7 +982,7 @@ jobs:
             os: windows-2022
             cmake_generator: "MinGW Makefiles"
 
-    timeout-minutes: 30
+    timeout-minutes: 60
     runs-on: ${{matrix.os}}
 
     steps:
@@ -987,15 +1018,13 @@ jobs:
             rmdir /s /q "..\snapshot"
             git submodule update --init tools/boostdep
             python tools/boostdep/depinst/depinst.py --git_args "--jobs %GIT_FETCH_JOBS%" %LIBRARY%
-            if "${{matrix.cmake_tests}}" == "" (
-                cmd /c bootstrap
-                b2 -d0 headers
-            )
 
       - name: Run tests
         if: matrix.cmake_tests == ''
         run: |
             cd boost-root
+            cmd /c bootstrap
+            b2 -d0 headers
             set "B2_ARGS=-j %NUMBER_OF_PROCESSORS% toolset=${{matrix.toolset}} embed-manifest-via=linker"
             if not "${{matrix.build_variant}}" == "" ( set "B2_ARGS=%B2_ARGS% variant=${{matrix.build_variant}}" ) else ( set "B2_ARGS=%B2_ARGS% variant=%DEFAULT_BUILD_VARIANT%" )
             if not "${{matrix.instruction_set}}" == "" (
@@ -1043,3 +1072,294 @@ jobs:
             ctest -C Release --output-on-failure --no-tests=error -j %NUMBER_OF_PROCESSORS%
             cd ../__build_shared__
             ctest -C Release --output-on-failure --no-tests=error -j %NUMBER_OF_PROCESSORS%
+
+  MSYS2:
+    defaults:
+      run:
+        shell: msys2 {0}
+
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - sys: MINGW32
+            toolset: gcc
+            cxxstd: '11-gnu,14-gnu,17-gnu,20-gnu,23-gnu,26-gnu'
+          - sys: MINGW64
+            toolset: gcc
+            cxxstd: '11-gnu,14-gnu,17-gnu,20-gnu,23-gnu,26-gnu'
+
+          - name: CMake MinGW32 tests
+            sys: MINGW32
+            cmake_tests: 1
+            cmake_generator: "Ninja"
+          - name: CMake MinGW64 tests
+            sys: MINGW64
+            cmake_tests: 1
+            cmake_generator: "Ninja"
+
+    timeout-minutes: 60
+    runs-on: windows-latest
+
+    steps:
+      - name: Setup MSYS2 environment
+        uses: msys2/setup-msys2@v2
+        with:
+          msystem: ${{matrix.sys}}
+          update: true
+          install: git python
+          pacboy: gcc:p cmake:p ninja:p
+
+      - name: Setup Boost
+        run: |
+            echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
+            LIBRARY=${GITHUB_REPOSITORY#*/}
+            echo LIBRARY: $LIBRARY
+            echo "LIBRARY=$LIBRARY" >> $GITHUB_ENV
+            echo GITHUB_BASE_REF: $GITHUB_BASE_REF
+            echo GITHUB_REF: $GITHUB_REF
+            REF=${GITHUB_BASE_REF:-$GITHUB_REF}
+            REF=${REF#refs/heads/}
+            echo REF: $REF
+            BOOST_BRANCH=develop && [ "$REF" = "master" ] && BOOST_BRANCH=master || true
+            echo BOOST_BRANCH: $BOOST_BRANCH
+            BUILD_JOBS=$((nproc || sysctl -n hw.ncpu) 2> /dev/null)
+            echo "BUILD_JOBS=$BUILD_JOBS" >> $GITHUB_ENV
+            echo "CMAKE_BUILD_PARALLEL_LEVEL=$BUILD_JOBS" >> $GITHUB_ENV
+            mkdir -p snapshot
+            cd snapshot
+            echo "Downloading library snapshot: https://github.com/${GITHUB_REPOSITORY}/archive/${GITHUB_SHA}.tar.gz"
+            curl -L --retry "$NET_RETRY_COUNT" -o "${LIBRARY}-${GITHUB_SHA}.tar.gz" "https://github.com/${GITHUB_REPOSITORY}/archive/${GITHUB_SHA}.tar.gz"
+            tar -xf "${LIBRARY}-${GITHUB_SHA}.tar.gz"
+            if [ ! -d "${LIBRARY}-${GITHUB_SHA}" ]
+            then
+                echo "Library snapshot does not contain the library directory ${LIBRARY}-${GITHUB_SHA}:"
+                ls -la
+                exit 1
+            fi
+            rm -f "${LIBRARY}-${GITHUB_SHA}.tar.gz"
+            cd ..
+            git clone -b "$BOOST_BRANCH" --depth 1 "https://github.com/boostorg/boost.git" "boost-root"
+            cd boost-root
+            mkdir -p libs
+            rm -rf "libs/$LIBRARY"
+            mv -f "../snapshot/${LIBRARY}-${GITHUB_SHA}" "libs/$LIBRARY"
+            rm -rf "../snapshot"
+            git submodule update --init tools/boostdep
+            python tools/boostdep/depinst/depinst.py --git_args "--jobs $GIT_FETCH_JOBS" --include example "$LIBRARY"
+
+      - name: Run tests
+        if: matrix.cmake_tests == ''
+        run: |
+            cd boost-root
+            ./bootstrap.sh
+            ./b2 -d0 headers
+            B2_ARGS=("-j" "$BUILD_JOBS" "toolset=${{matrix.toolset}}" "cxxstd=${{matrix.cxxstd}}")
+            if [ -n "${{matrix.build_variant}}" ]
+            then
+                B2_ARGS+=("variant=${{matrix.build_variant}}")
+            else
+                B2_ARGS+=("variant=$DEFAULT_BUILD_VARIANT")
+            fi
+            if [ -n "${{matrix.threading}}" ]
+            then
+                B2_ARGS+=("threading=${{matrix.threading}}")
+            fi
+            if [ -n "${{matrix.ubsan}}" ]
+            then
+                export UBSAN_OPTIONS="print_stacktrace=1"
+                B2_ARGS+=("cxxflags=-fsanitize=undefined -fno-sanitize-recover=undefined" "linkflags=-fsanitize=undefined" "define=UBSAN=1" "debug-symbols=on" "visibility=global")
+            fi
+            if [ -n "${{matrix.cxxflags}}" ]
+            then
+                B2_ARGS+=("cxxflags=${{matrix.cxxflags}}")
+            fi
+            if [ -n "${{matrix.linkflags}}" ]
+            then
+                B2_ARGS+=("linkflags=${{matrix.linkflags}}")
+            fi
+            if [ -n "${{matrix.instruction_set}}" ]
+            then
+                if [ "${{matrix.instruction_set}}" != "-" ]
+                then
+                    B2_ARGS+=("instruction-set=${{matrix.instruction_set}}")
+                fi
+            elif [ -n "$DEFAULT_INSTRUCTION_SET" ]
+            then
+                B2_ARGS+=("instruction-set=$DEFAULT_INSTRUCTION_SET")
+            fi
+            B2_ARGS+=("libs/$LIBRARY/test")
+            ./b2 "${B2_ARGS[@]}"
+
+      - name: Build CMake tests
+        if: matrix.cmake_tests
+        run: |
+            if [ -n "${{matrix.cmake_generator}}" ]
+            then
+                export "CMAKE_GENERATOR=${{matrix.cmake_generator}}"
+            fi
+            cd boost-root
+            mkdir __build_static__ && cd __build_static__
+            cmake -DBOOST_INCLUDE_LIBRARIES=$LIBRARY -DBUILD_TESTING=ON ..
+            cmake --build . --target tests -j $BUILD_JOBS
+            cd ..
+            mkdir __build_shared__ && cd __build_shared__
+            cmake -DBOOST_INCLUDE_LIBRARIES=$LIBRARY -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON ..
+            cmake --build . --target tests -j $BUILD_JOBS
+
+      - name: Run CMake tests
+        if: matrix.cmake_tests
+        run: |
+            cd boost-root
+            cd __build_static__
+            ctest --output-on-failure --no-tests=error -j $BUILD_JOBS
+            cd ../__build_shared__
+            ctest --output-on-failure --no-tests=error -j $BUILD_JOBS
+
+  cygwin:
+    defaults:
+      run:
+        shell: bash
+
+    env:
+      SHELLOPTS: igncr
+      CYGWIN: winsymlinks:native
+
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          # Note: Some tests fail with no error output on Cygwin, if AVX is enabled. Reasons unknown.
+          - toolset: gcc
+            cxxstd: "11-gnu,14-gnu,17-gnu,20-gnu,23-gnu,26-gnu"
+            instruction_set: "-"
+            cxxflags: "-mcx16"
+            build_variant: debug
+
+          - name: CMake Cygwin tests
+            cmake_tests: 1
+            cmake_generator: "Ninja"
+
+    timeout-minutes: 60
+    runs-on: windows-latest
+
+    steps:
+      - name: Configure git
+        run: |
+          git config --global core.autocrlf input
+
+      - name: Install Cygwin
+        uses: cygwin/cygwin-install-action@v6
+        with:
+          packages:
+            gcc-g++
+            cmake
+            ninja
+
+      - name: Setup Boost
+        run: |
+            echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
+            LIBRARY=${GITHUB_REPOSITORY#*/}
+            echo LIBRARY: $LIBRARY
+            echo "LIBRARY=$LIBRARY" >> $GITHUB_ENV
+            echo GITHUB_BASE_REF: $GITHUB_BASE_REF
+            echo GITHUB_REF: $GITHUB_REF
+            REF=${GITHUB_BASE_REF:-$GITHUB_REF}
+            REF=${REF#refs/heads/}
+            echo REF: $REF
+            BOOST_BRANCH=develop && [ "$REF" = "master" ] && BOOST_BRANCH=master || true
+            echo BOOST_BRANCH: $BOOST_BRANCH
+            BUILD_JOBS=$((nproc) 2> /dev/null)
+            echo "BUILD_JOBS=$BUILD_JOBS" >> $GITHUB_ENV
+            echo "CMAKE_BUILD_PARALLEL_LEVEL=$BUILD_JOBS" >> $GITHUB_ENV
+            DEPINST_ARGS=("--git_args" "--jobs $GIT_FETCH_JOBS")
+            mkdir -p snapshot
+            cd snapshot
+            echo "Downloading library snapshot: https://github.com/${GITHUB_REPOSITORY}/archive/${GITHUB_SHA}.tar.gz"
+            curl -L --retry "$NET_RETRY_COUNT" -o "${LIBRARY}-${GITHUB_SHA}.tar.gz" "https://github.com/${GITHUB_REPOSITORY}/archive/${GITHUB_SHA}.tar.gz"
+            tar -xf "${LIBRARY}-${GITHUB_SHA}.tar.gz"
+            if [ ! -d "${LIBRARY}-${GITHUB_SHA}" ]
+            then
+                echo "Library snapshot does not contain the library directory ${LIBRARY}-${GITHUB_SHA}:"
+                ls -la
+                exit 1
+            fi
+            rm -f "${LIBRARY}-${GITHUB_SHA}.tar.gz"
+            cd ..
+            git clone -b "$BOOST_BRANCH" --depth 1 "https://github.com/boostorg/boost.git" "boost-root"
+            cd boost-root
+            mkdir -p libs
+            rm -rf "libs/$LIBRARY"
+            mv -f "../snapshot/${LIBRARY}-${GITHUB_SHA}" "libs/$LIBRARY"
+            rm -rf "../snapshot"
+            git submodule update --init tools/boostdep
+            DEPINST_ARGS+=("$LIBRARY")
+            python tools/boostdep/depinst/depinst.py "${DEPINST_ARGS[@]}"
+
+      - name: Run tests
+        if: matrix.cmake_tests == ''
+        run: |
+            cd boost-root
+            ./bootstrap.sh
+            ./b2 -d0 headers
+            B2_ARGS=("-j" "$BUILD_JOBS" "toolset=${{matrix.toolset}}" "cxxstd=${{matrix.cxxstd}}" "address-model=64")
+            if [ -n "${{matrix.build_variant}}" ]
+            then
+                B2_ARGS+=("variant=${{matrix.build_variant}}")
+            else
+                B2_ARGS+=("variant=$DEFAULT_BUILD_VARIANT")
+            fi
+            if [ -n "${{matrix.threading}}" ]
+            then
+                B2_ARGS+=("threading=${{matrix.threading}}")
+            fi
+            if [ -n "${{matrix.ubsan}}" ]
+            then
+                export UBSAN_OPTIONS="print_stacktrace=1"
+                B2_ARGS+=("cxxflags=-fsanitize=undefined -fno-sanitize-recover=undefined" "linkflags=-fsanitize=undefined" "define=UBSAN=1" "debug-symbols=on" "visibility=global")
+            fi
+            if [ -n "${{matrix.cxxflags}}" ]
+            then
+                B2_ARGS+=("cxxflags=${{matrix.cxxflags}}")
+            fi
+            if [ -n "${{matrix.linkflags}}" ]
+            then
+                B2_ARGS+=("linkflags=${{matrix.linkflags}}")
+            fi
+            if [ -n "${{matrix.instruction_set}}" ]
+            then
+                if [ "${{matrix.instruction_set}}" != "-" ]
+                then
+                    B2_ARGS+=("instruction-set=${{matrix.instruction_set}}")
+                fi
+            elif [ -n "$DEFAULT_INSTRUCTION_SET" ]
+            then
+                B2_ARGS+=("instruction-set=$DEFAULT_INSTRUCTION_SET")
+            fi
+            B2_ARGS+=("libs/$LIBRARY/test")
+            ./b2 "${B2_ARGS[@]}"
+
+      - name: Build CMake tests
+        if: matrix.cmake_tests
+        run: |
+            if [ -n "${{matrix.cmake_generator}}" ]
+            then
+                export "CMAKE_GENERATOR=${{matrix.cmake_generator}}"
+            fi
+            cd boost-root
+            mkdir __build_static__ && cd __build_static__
+            cmake -DBOOST_INCLUDE_LIBRARIES=$LIBRARY -DBUILD_TESTING=ON ..
+            cmake --build . --target tests -j $BUILD_JOBS
+            cd ..
+            mkdir __build_shared__ && cd __build_shared__
+            cmake -DBOOST_INCLUDE_LIBRARIES=$LIBRARY -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON ..
+            cmake --build . --target tests -j $BUILD_JOBS
+
+      - name: Run CMake tests
+        if: matrix.cmake_tests
+        run: |
+            cd boost-root
+            cd __build_static__
+            ctest --output-on-failure --no-tests=error -j $BUILD_JOBS
+            cd ../__build_shared__
+            ctest --output-on-failure --no-tests=error -j $BUILD_JOBS
